<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Buku;

class BukuSeeder extends Seeder
{
    /**
     * Seed data buku dengan berbagai kategori
     */
    public function run(): void
    {
        $bukus = [
            // Kategori Pemrograman (ID: 1)
            [
                'kategori_id' => 1,
                'judul' => 'Pemrograman Web dengan Laravel',
                'penulis' => 'Budi Raharjo',
                'penerbit' => 'Informatika',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-01-1',
                'jumlah_halaman' => 450,
                'deskripsi' => 'Buku panduan lengkap membangun aplikasi web modern menggunakan framework Laravel. Cocok untuk pemula hingga menengah.',
                'bahasa' => 'Indonesia',
                'harga' => 125000,
                'berat' => 600,
                'stok' => 25,
                'is_active' => true,
                'terjual' => 15,
            ],
            [
                'kategori_id' => 1,
                'judul' => 'Belajar JavaScript dari Nol',
                'penulis' => 'Ahmad Fauzi',
                'penerbit' => 'Elex Media',
                'tahun_terbit' => 2024,
                'isbn' => '978-602-1234-02-8',
                'jumlah_halaman' => 380,
                'deskripsi' => 'Panduan praktis belajar JavaScript untuk pemula. Disertai dengan contoh kasus dan latihan.',
                'bahasa' => 'Indonesia',
                'harga' => 95000,
                'berat' => 500,
                'stok' => 30,
                'is_active' => true,
                'terjual' => 20,
            ],
            [
                'kategori_id' => 1,
                'judul' => 'Mahir PHP 8 dan MySQL',
                'penulis' => 'Siti Rahmawati',
                'penerbit' => 'Andi Publisher',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-03-5',
                'jumlah_halaman' => 520,
                'deskripsi' => 'Buku komprehensif tentang PHP 8 dan MySQL untuk pengembangan web dinamis.',
                'bahasa' => 'Indonesia',
                'harga' => 135000,
                'berat' => 650,
                'stok' => 18,
                'is_active' => true,
                'terjual' => 12,
            ],

            // Kategori Novel (ID: 2)
            [
                'kategori_id' => 2,
                'judul' => 'Laskar Pelangi',
                'penulis' => 'Andrea Hirata',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2005,
                'isbn' => '978-979-3062-79-2',
                'jumlah_halaman' => 534,
                'deskripsi' => 'Novel tentang kehidupan dan perjuangan sepuluh anak dari keluarga miskin di Belitung.',
                'bahasa' => 'Indonesia',
                'harga' => 89000,
                'berat' => 400,
                'stok' => 40,
                'is_active' => true,
                'terjual' => 150,
            ],
            [
                'kategori_id' => 2,
                'judul' => 'Bumi Manusia',
                'penulis' => 'Pramoedya Ananta Toer',
                'penerbit' => 'Lentera Dipantara',
                'tahun_terbit' => 2020,
                'isbn' => '978-602-1234-04-2',
                'jumlah_halaman' => 535,
                'deskripsi' => 'Novel sejarah Indonesia yang mengisahkan kehidupan seorang anak pribumi pada masa kolonial.',
                'bahasa' => 'Indonesia',
                'harga' => 105000,
                'berat' => 450,
                'stok' => 35,
                'is_active' => true,
                'terjual' => 80,
            ],
            [
                'kategori_id' => 2,
                'judul' => 'Perahu Kertas',
                'penulis' => 'Dee Lestari',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2009,
                'isbn' => '978-602-1234-05-9',
                'jumlah_halaman' => 456,
                'deskripsi' => 'Novel romantis tentang perjalanan dua insan yang saling mencari jati diri.',
                'bahasa' => 'Indonesia',
                'harga' => 92000,
                'berat' => 380,
                'stok' => 28,
                'is_active' => true,
                'terjual' => 95,
            ],

            // Kategori Bisnis & Ekonomi (ID: 3)
            [
                'kategori_id' => 3,
                'judul' => 'Rich Dad Poor Dad - Edisi Indonesia',
                'penulis' => 'Robert Kiyosaki',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2022,
                'isbn' => '978-602-1234-06-6',
                'jumlah_halaman' => 312,
                'deskripsi' => 'Buku bestseller tentang literasi finansial dan cara mencapai kebebasan finansial.',
                'bahasa' => 'Indonesia',
                'harga' => 115000,
                'berat' => 350,
                'stok' => 45,
                'is_active' => true,
                'terjual' => 200,
            ],
            [
                'kategori_id' => 3,
                'judul' => 'Strategi Bisnis Digital di Era 4.0',
                'penulis' => 'Hendro Wibowo',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-07-3',
                'jumlah_halaman' => 280,
                'deskripsi' => 'Panduan praktis membangun dan mengembangkan bisnis digital di Indonesia.',
                'bahasa' => 'Indonesia',
                'harga' => 98000,
                'berat' => 320,
                'stok' => 22,
                'is_active' => true,
                'terjual' => 35,
            ],

            // Kategori Sejarah (ID: 4)
            [
                'kategori_id' => 4,
                'judul' => 'Sejarah Indonesia Modern',
                'penulis' => 'MC Ricklefs',
                'penerbit' => 'Serambi',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-08-0',
                'jumlah_halaman' => 680,
                'deskripsi' => 'Kajian komprehensif tentang sejarah Indonesia dari masa kolonial hingga modern.',
                'bahasa' => 'Indonesia',
                'harga' => 175000,
                'berat' => 800,
                'stok' => 15,
                'is_active' => true,
                'terjual' => 25,
            ],
            [
                'kategori_id' => 4,
                'judul' => 'Jejak Langkah Pahlawan Indonesia',
                'penulis' => 'Agus Setiawan',
                'penerbit' => 'Kompas',
                'tahun_terbit' => 2022,
                'isbn' => '978-602-1234-09-7',
                'jumlah_halaman' => 420,
                'deskripsi' => 'Kisah inspiratif para pahlawan yang berjuang untuk kemerdekaan Indonesia.',
                'bahasa' => 'Indonesia',
                'harga' => 110000,
                'berat' => 480,
                'stok' => 20,
                'is_active' => true,
                'terjual' => 40,
            ],

            // Kategori Agama & Spiritual (ID: 5)
            [
                'kategori_id' => 5,
                'judul' => 'The Power of Kepasrahan',
                'penulis' => 'Ary Ginanjar Agustian',
                'penerbit' => 'Arga Publishing',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-10-3',
                'jumlah_halaman' => 295,
                'deskripsi' => 'Buku pengembangan diri yang menggabungkan nilai spiritual dan praktis dalam kehidupan.',
                'bahasa' => 'Indonesia',
                'harga' => 88000,
                'berat' => 300,
                'stok' => 32,
                'is_active' => true,
                'terjual' => 55,
            ],

            // Kategori Anak-anak (ID: 6)
            [
                'kategori_id' => 6,
                'judul' => 'Dongeng Anak Nusantara',
                'penulis' => 'Murti Bunanta',
                'penerbit' => 'Balai Pustaka',
                'tahun_terbit' => 2024,
                'isbn' => '978-602-1234-11-0',
                'jumlah_halaman' => 180,
                'deskripsi' => 'Kumpulan dongeng tradisional Indonesia yang dikemas menarik untuk anak-anak.',
                'bahasa' => 'Indonesia',
                'harga' => 65000,
                'berat' => 250,
                'stok' => 50,
                'is_active' => true,
                'terjual' => 70,
            ],
            [
                'kategori_id' => 6,
                'judul' => 'Petualangan Si Kancil',
                'penulis' => 'Tim Penulis Anak',
                'penerbit' => 'Mizan',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-12-7',
                'jumlah_halaman' => 120,
                'deskripsi' => 'Cerita petualangan Si Kancil yang lucu dan mendidik untuk anak-anak.',
                'bahasa' => 'Indonesia',
                'harga' => 55000,
                'berat' => 200,
                'stok' => 60,
                'is_active' => true,
                'terjual' => 85,
            ],

            // Kategori Komik & Manga (ID: 7)
            [
                'kategori_id' => 7,
                'judul' => 'Si Juki: Kumpulan Strip Komik',
                'penulis' => 'Faza Meonk',
                'penerbit' => 'Bukune',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-13-4',
                'jumlah_halaman' => 200,
                'deskripsi' => 'Kumpulan komik strip Si Juki yang menghibur dan relevan dengan kehidupan sehari-hari.',
                'bahasa' => 'Indonesia',
                'harga' => 75000,
                'berat' => 280,
                'stok' => 35,
                'is_active' => true,
                'terjual' => 90,
            ],

            // Kategori Pendidikan (ID: 8)
            [
                'kategori_id' => 8,
                'judul' => 'Panduan Belajar Matematika SMA',
                'penulis' => 'Tim Guru Matematika',
                'penerbit' => 'Erlangga',
                'tahun_terbit' => 2024,
                'isbn' => '978-602-1234-14-1',
                'jumlah_halaman' => 550,
                'deskripsi' => 'Buku panduan lengkap matematika SMA dengan pembahasan soal dan latihan.',
                'bahasa' => 'Indonesia',
                'harga' => 145000,
                'berat' => 700,
                'stok' => 40,
                'is_active' => true,
                'terjual' => 110,
            ],
            [
                'kategori_id' => 8,
                'judul' => 'Kamus Bahasa Indonesia Lengkap',
                'penulis' => 'Tim Penyusun Kamus',
                'penerbit' => 'Balai Pustaka',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-15-8',
                'jumlah_halaman' => 1200,
                'deskripsi' => 'Kamus Bahasa Indonesia yang komprehensif dan up-to-date.',
                'bahasa' => 'Indonesia',
                'harga' => 185000,
                'berat' => 950,
                'stok' => 25,
                'is_active' => true,
                'terjual' => 45,
            ],

            // Kategori Kesehatan (ID: 9)
            [
                'kategori_id' => 9,
                'judul' => 'Hidup Sehat Cara Rasulullah',
                'penulis' => 'Dr. Zaidul Akbar',
                'penerbit' => 'Sygma',
                'tahun_terbit' => 2023,
                'isbn' => '978-602-1234-16-5',
                'jumlah_halaman' => 320,
                'deskripsi' => 'Panduan hidup sehat berdasarkan sunnah Rasulullah SAW dengan pendekatan medis modern.',
                'bahasa' => 'Indonesia',
                'harga' => 98000,
                'berat' => 350,
                'stok' => 38,
                'is_active' => true,
                'terjual' => 125,
            ],

            // Kategori Seni & Budaya (ID: 10)
            [
                'kategori_id' => 10,
                'judul' => 'Kesenian Tradisional Indonesia',
                'penulis' => 'I Wayan Dibia',
                'penerbit' => 'ISI Press',
                'tahun_terbit' => 2022,
                'isbn' => '978-602-1234-17-2',
                'jumlah_halaman' => 385,
                'deskripsi' => 'Kajian mendalam tentang berbagai kesenian tradisional Indonesia dari Sabang sampai Merauke.',
                'bahasa' => 'Indonesia',
                'harga' => 128000,
                'berat' => 450,
                'stok' => 20,
                'is_active' => true,
                'terjual' => 30,
            ],
        ];

        foreach ($bukus as $buku) {
            // Generate slug dari judul
            $buku['slug'] = Str::slug($buku['judul']);
            Buku::create($buku);
        }
    }
}
